Add api/v3 in example
I'm using Github Enterprise and Github OAuth.
Chef-Guard was giving me an error before I added '/api/v3' to the end of serverurl:
```
ERROR:  Failed to update node-01 node for anton in Github: invalid character '<' looking for beginning of value
```

Since most of cookbook users just uncomment example attributes (like me) it's better to provide the right format in example.